### ISSUE TITLE
Installation problem on macOS

### ISSUE THREAD

**Issue by cdesgrange** [3fon3fonov/exostriker#96] opened 2021-12-15 15:48 UTC
Hi Trifon,

I downloaded exostriker via 

$ pip install git+https://github.com/3fon3fonov/exostriker    

but problems show up while running

$ exostriker    

it shows me: 

---------------------------------------------------------------
New source code available: Updating Keplerian Simplex
New source code available: Updating Keplerian L-M
New source code available: Updating N-body Simplex
New source code available: Updating N-body L-M
New source code available: Updating Mixed Simplex

Something went wrong!!! 

Perhaps you do not have user permission to compile code in the Exo-Striker directory?
Or perhaps, you do not have 'gfortran' installed? 

Trying 

$ gfortran -v 

returned:

[['Utilisation', 'des', 'specs', 'internes.'], ['COLLECT_GCC=gfortran'], ['COLLECT_LTO_WRAPPER=/usr/local/gfortran/libexec/gcc/x86_64-apple-darwin20/11.2.0/lto-wrapper'], ['Cible', ':', 'x86_64-apple-darwin20'], ['Configuré', 'avec:', '../gcc-11.2.0/configure', '--prefix=/usr/local/gfortran', '--with-gmp=/Users/fx/devel/gcc/deps-static/x86_64', '--enable-languages=c,c++,fortran,objc,obj-c++,d', '--build=x86_64-apple-darwin20', '--disable-multilib', '--with-native-system-header-dir=/usr/include', '--with-sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk', '--enable-libphobos', '--without-build-config'], ['Modèle', 'de', 'thread:', 'posix'], ['Algorithmes', 'de', 'compression', 'LTO', 'supportés:', 'zlib'], ['gcc', 'version', '11.2.0', '(GCC)']]    

If 'gfortran' is not found, please install it and try again. Else, please open a GitHub issue here:

https://github.com/3fon3fonov/exostriker/issues
        
[5, 9]
Traceback (most recent call last):
  File "/Users/user/opt/anaconda3/bin/exostriker", line 4, in <module>
    __import__('pkg_resources').run_script('exostriker==0.65', 'exostriker')
  File "/Users/user/opt/anaconda3/lib/python3.9/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/user/opt/anaconda3/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1448, in run_script
    exec(code, namespace, namespace)
  File "/Users/user/opt/anaconda3/lib/python3.9/site-packages/exostriker-0.65-py3.9.egg/EGG-INFO/scripts/exostriker", line 2, in <module>
    import exostriker
  File "/Users/user/opt/anaconda3/lib/python3.9/site-packages/exostriker-0.65-py3.9.egg/exostriker/__init__.py", line 1, in <module>
    from exostriker import gui
  File "/Users/user/opt/anaconda3/lib/python3.9/site-packages/exostriker-0.65-py3.9.egg/exostriker/gui.py", line 44, in <module>
    import pyqtgraph as pg
  File "/Users/user/opt/anaconda3/lib/python3.9/site-packages/exostriker-0.65-py3.9.egg/exostriker/lib/pyqtgraph/__init__.py", line 13, in <module>
    from .Qt import QtCore, QtGui, mkQApp
  File "/Users/user/opt/anaconda3/lib/python3.9/site-packages/exostriker-0.65-py3.9.egg/exostriker/lib/pyqtgraph/Qt/__init__.py", line 362, in <module>
    raise Exception('pyqtgraph requires Qt version >= %d.%d  (your version is %s)' % (versionReq[0], versionReq[1], QtVersion))
Exception: pyqtgraph requires Qt version >= 5.12  (your version is 5.9.7)

zsh: abort      exostriker

---------------------------------------------------------------

  

I am on macOS Big Sur, version 11.2.1., I am using python3, packages gfortran, csh and pip are already installed. The problem seems to be because of the Qt version, too old. Yet Qt is installed within exostriker, with the good version I supposed, so I do not understand.

I do not get which package I should install. Qt does not seem to be a package which I could download with "pip install", as 
$ pip install Qt                                 
ERROR: Could not find a version that satisfies the requirement Qt (from versions: none)
ERROR: No matching distribution found for Qt

I have also tried to install again "pyqtgraph" and "pyside6", hoping for a more recent version solving the problems, but it did not work. 

Do you have any idea?

Thank you.
Célia

**Comment by 3fon3fonov** [comment] 2021-12-15 16:16
This is PyQt5 anaconda3 problem, gfortran anaconda3 problem, or you somehow install the tool where you cannot write: Check these issues:

https://github.com/3fon3fonov/exostriker/issues/79
https://github.com/3fon3fonov/exostriker/issues/75

Try with these, and if does not work, let me know, and I will have a deeper look.

**Comment by cdesgrange** [comment] 2021-12-20 10:04
I think I had both of these problems

The PyQt5 problem is solved (hopefully). As in the issue #79,  I created a new environment in which I installed exostriker. Now, I am able to open exostriker. Yet, executing

% exostriker

print this following error message (apparently from gfortran)

---------------------------------------------------------------------------------------
exostriker
New source code available: Updating Keplerian Simplex
New source code available: Updating Keplerian L-M
New source code available: Updating N-body Simplex
New source code available: Updating N-body L-M
New source code available: Updating Mixed Simplex

Something went wrong!!! 

Perhaps you do not have user permission to compile code in the Exo-Striker directory?
Or perhaps, you do not have 'gfortran' installed? 

Trying 

$ gfortran -v 

returned:

[['Utilisation', 'des', 'specs', 'internes.'], ['COLLECT_GCC=gfortran'], ['COLLECT_LTO_WRAPPER=/usr/local/gfortran/libexec/gcc/x86_64-apple-darwin20/11.2.0/lto-wrapper'], ['Cible', ':', 'x86_64-apple-darwin20'], ['Configuré', 'avec:', '../gcc-11.2.0/configure', '--prefix=/usr/local/gfortran', '--with-gmp=/Users/fx/devel/gcc/deps-static/x86_64', '--enable-languages=c,c++,fortran,objc,obj-c++,d', '--build=x86_64-apple-darwin20', '--disable-multilib', '--with-native-system-header-dir=/usr/include', '--with-sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk', '--enable-libphobos', '--without-build-config'], ['Modèle', 'de', 'thread:', 'posix'], ['Algorithmes', 'de', 'compression', 'LTO', 'supportés:', 'zlib'], ['gcc', 'version', '11.2.0', '(GCC)']]    

If 'gfortran' is not found, please install it and try again. Else, please open a GitHub issue here:

https://github.com/3fon3fonov/exostriker/issues
---------------------------------------------------------------------------------------

I looked into the #75 issue, and gfortran is well installed:

---------------------------------------------------------------------------------------
% gfortran -v
Utilisation des specs internes.
COLLECT_GCC=gfortran
COLLECT_LTO_WRAPPER=/usr/local/gfortran/libexec/gcc/x86_64-apple-darwin20/11.2.0/lto-wrapper
Cible : x86_64-apple-darwin20
Configuré avec: ../gcc-11.2.0/configure --prefix=/usr/local/gfortran --with-gmp=/Users/fx/devel/gcc/deps-static/x86_64 --enable-languages=c,c++,fortran,objc,obj-c++,d --build=x86_64-apple-darwin20 --disable-multilib --with-native-system-header-dir=/usr/include --with-sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk --enable-libphobos --without-build-config
Modèle de thread: posix
Algorithmes de compression LTO supportés: zlib
gcc version 11.2.0 (GCC) 
---------------------------------------------------------------------------------------

As mentioned in issue #75, I gave me the rights to execute all the scripts in exostriker folder.

Note that running exostriker, opens me the exostriker interface, where I can load transit data without problems, but not RV data. When I try to load RV data, the interface windows closes and exostriker aborts:

---------------------------------------------------------------------------------------
(following previous message concerning "If gfortan is not found (...) open a GitHub issue here : ...)

qt.qpa.fonts: Populating font family aliases took 1193 ms. Replace uses of missing font family "Monospace" with one that exists to avoid this cost. 
qt.qpa.window: <QNSWindow: 0x7fa3c87a3e30; contentView=<QNSView: 0x7fa3c87a3600; QCocoaWindow(0x7fa3c87a34f0, window=QWidgetWindow(0x7fa3c87a2ca0, name="MainWindowClassWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.

zsh: abort      exostriker
---------------------------------------------------------------------------------------

Thanks!
Célia

**Comment by 3fon3fonov** [comment] 2021-12-21 09:16
Try to remove the exostriker and install with sudo, e,g.:

sudo pip3 install git+https://github.com/3fon3fonov/exostriker 

#or whatever pip you are using to install Python3 packages

Then try:

$exostriker


Else, just download the git repository with "git clone", say in your home directory, e.g.,

$ git clone https://github.com/3fon3fonov/exostriker
$ cd exostriker
$ python3.8 exostriker_gui.py -debug #debug to see any errors on the bash shell

If this does not work, please contact the MPIA-IT guys to give you instructions. I still suspect that you have no rights to install fortran code on the directory where the exostriker is stored.  I do not have any problems on MAC OS, so this is puzzling. 
BTW, if you cannot open RV files means you may not have access to the /tmp directory, which is also weird. 


Please report in any case!

**Comment by cdesgrange** [comment] 2021-12-22 14:07
I tried as you said, same problem.

Regarding fortran, I have uninstalled and installed again fortran via gcc :

% brew install gcc

gcc and gfortran are well located there:

/usr/bin/gcc
/usr/local/bin/gfortran

The gcc version is 4.8.5.

Do you mean gcc and gfortran should be in the exostriker folder ?

My computer is not from the MPIA, but do you think I should still contact the MPIA-IT guys?


Actually, running ls /tmp gives me something:

------------------------------------------------------------------------------------------

%ls /tmp
30A0A2F4-CFAD-48B0-B590-4DEF623993BE-vpndownloader	hasfunction-laz8dw08
boost_interprocess					hasfunction-pv242th3
com.apple.launchd.iI3IyXhza4				hasfunction-uh0wyolu
com.google.Keystone					hasfunction-v0x0y8xx
es2							hasfunction-y6m3_dt8
hasfunction-216fnups

------------------------------------------------------------------------------------------

 
here the message printed from python (version 3.9.7) while running

python exostriker_gui.py -debug  

------------------------------------------------------------------------------------------

% python exostriker_gui.py -debug                                            
New source code available: Updating Keplerian Simplex
New source code available: Updating Keplerian L-M
New source code available: Updating N-body Simplex
New source code available: Updating N-body L-M
New source code available: Updating Mixed Simplex

Something went wrong!!! 

Perhaps you do not have user permission to compile code in the Exo-Striker directory?
Or perhaps, you do not have 'gfortran' installed? 

Trying 

$ gfortran -v 

returned:

[['Using', 'built-in', 'specs.'], ['COLLECT_GCC=gfortran'], ['COLLECT_LTO_WRAPPER=/Users/user/opt/anaconda3/envs/exostriker-env/bin/../libexec/gcc/x86_64-apple-darwin11.4.2/4.8.5/lto-wrapper'], ['Target:', 'x86_64-apple-darwin11.4.2'], ['Configured', 'with:', './configure', '--prefix=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac', '--with-gxx-include-dir=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/gcc/include/c++', '--bindir=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin', '--datarootdir=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/share', '--libdir=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib', '--with-gmp=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac', '--with-mpfr=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac', '--with-mpc=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac', '--with-isl=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac', '--with-cloog=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac', "--with-boot-ldflags='-Wl,-headerpad_max_install_names", '-Wl,-L/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib', "-Wl,-L/usr/lib'", "--with-stage1-ldflags='-Wl,-headerpad_max_install_names", '-Wl,-L/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib', "-Wl,-L/usr/lib'", '--enable-checking=release', '--with-tune=generic', '--disable-multilib'], ['Thread', 'model:', 'posix'], ['gcc', 'version', '4.8.5', '(GCC)']]    

If 'gfortran' is not found, please install it and try again. Else, please open a GitHub issue here:

https://github.com/3fon3fonov/exostriker/issues
        
qt.qpa.fonts: Populating font family aliases took 1117 ms. Replace uses of missing font family "Monospace" with one that exists to avoid this cost. 
qt.qpa.window: <QNSWindow: 0x7feaa65d7490; contentView=<QNSView: 0x7feaa65d6990; QCocoaWindow(0x7feaa65d6150, window=QWidgetWindow(0x7feaa65d5450, name="MainWindowClassWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.
wotan==1.10
ttvfast==0.3.0
transitleastsquares==1.0.24
scipy==1.7.3
qtconsole==5.2.2
PyQt5==5.15.6
pathos==0.2.8
numpy==1.20.3
matplotlib==3.3.1
jupyter==1.0.0
jupyter-client==7.1.0
ipykernel==6.6.0
emcee==3.1.1
dynesty==1.1
corner==2.2.1
celerite==0.4.2
New source code available: Updating Keplerian Simplex
New source code available: Updating Keplerian L-M
New source code available: Updating N-body Simplex
New source code available: Updating N-body L-M
New source code available: Updating Mixed Simplex

Something went wrong!!! 

Perhaps you do not have user permission to compile code in the Exo-Striker directory?
Or perhaps, you do not have 'gfortran' installed? 

Trying 

$ gfortran -v 

returned:

[['Using', 'built-in', 'specs.'], ['COLLECT_GCC=gfortran'], ['COLLECT_LTO_WRAPPER=/Users/user/opt/anaconda3/envs/exostriker-env/bin/../libexec/gcc/x86_64-apple-darwin11.4.2/4.8.5/lto-wrapper'], ['Target:', 'x86_64-apple-darwin11.4.2'], ['Configured', 'with:', './configure', '--prefix=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac', '--with-gxx-include-dir=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/gcc/include/c++', '--bindir=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin', '--datarootdir=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/share', '--libdir=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib', '--with-gmp=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac', '--with-mpfr=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac', '--with-mpc=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac', '--with-isl=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac', '--with-cloog=/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac', "--with-boot-ldflags='-Wl,-headerpad_max_install_names", '-Wl,-L/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib', "-Wl,-L/usr/lib'", "--with-stage1-ldflags='-Wl,-headerpad_max_install_names", '-Wl,-L/Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib', "-Wl,-L/usr/lib'", '--enable-checking=release', '--with-tune=generic', '--disable-multilib'], ['Thread', 'model:', 'posix'], ['gcc', 'version', '4.8.5', '(GCC)']]    

If 'gfortran' is not found, please install it and try again. Else, please open a GitHub issue here:

https://github.com/3fon3fonov/exostriker/issues
        
You are running a development version of the Exo-Striker (ver. 0.65). 
              
This version is almost full, but there are still some parts of the tool, which are in a 'Work in progress' state. Please, 'git pull' regularly to be up to date with the newest version.

Here you can get some more information from the tool's workflow, stdout/strerr, and piped results.
--- 0.016349315643310547 seconds ---

Reading fortran output resulted in 1 warnings:

1 Wrong data format in line 1 of fortran output, line skipped.

<class 'ValueError'> max() arg is an empty sequence <traceback object at 0x7feabe7b50c0>
===== 2021.12.22 15:12:04 =====
Traceback (most recent call last):
  File "/Users/user/opt/anaconda3/envs/exostriker-env/exostriker/exostriker/gui.py", line 5533, in showDialog_RV_input_file
    self.update_RV_file_buttons()
  File "/Users/user/opt/anaconda3/envs/exostriker-env/exostriker/exostriker/gui.py", line 5591, in update_RV_file_buttons
    self.init_correlations_combo()
  File "/Users/user/opt/anaconda3/envs/exostriker-env/exostriker/exostriker/gui.py", line 3857, in init_correlations_combo
    for i in range(max(fit.fit_results.idset)+1):
ValueError: max() arg is an empty sequence

zsh: abort      python exostriker_gui.py -debug

------------------------------------------------------------------------------------------

In the end, the line "--- 0.016349315643310547 seconds ---" is printed when I load transit data.

Lines just afterwards are printed when I load RV data (ex: hip5364.vels).

**Comment by 3fon3fonov** [comment] 2021-12-24 11:16
I think your gcc is way too old. Here is mine:

trifonov@lnx-n-0046:~$ gcc --version
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

i.e., my gfortran:

trifonov@lnx-n-0046:~$ gfortran --version
GNU Fortran (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

On my Mac OS is gcc/gfortran is 9.3.0 !!! 


Check this old thread, which point to anaconda3 problem:

https://github.com/3fon3fonov/exostriker/issues/53



Also make sure you have the RV ascii file format as follows:

BJD [m/s]   RV [m/s]   Sigma RV [m/s]



And finally, in the $exostriker directory run 

$ bash install_f77_opt.sh -O3
 
 bash install_f77_opt.sh -O3
 

Which in case your gfortran is OK, should exit with: "Installing the Fortran routines for a first time!" and no error!



p.s. if your computer is not MPIA-owned then there is no point to contact the MPIA -IT.



Let me know if upgrading your gfortran helped.

**Comment by 3fon3fonov** [comment] 2021-12-30 08:11
Somebody else reported (via e-mail) very similar issue on new MAC OS. I suspect there is some issue with gfortran on MAC OS, but so far I have limited info about your system(s). Celia, can you please report if upgrading the gfortran fixed your issue, and if not, please provide a summary of your system. I.e. MAC OS version, Python version, Anaconda if used, and gfortran/gcc version.

**Comment by charliezhang51** [comment] 2021-12-30 11:01
I had a very similar issue which was fixed by downloading another version of gfortran.

The current gfortran/gcc downloaded is

$ gcc --version

Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1

Apple clang version 13.0.0 (clang-1300.0.29.3)

Target: arm64-apple-darwin21.1.0

Thread model: posix

InstalledDir: /Library/Developer/CommandLineTools/usr/bin


$ gfortran --version

GNU Fortran (GCC) 12.0.0 20211218 (experimental)

Copyright (C) 2021 Free Software Foundation, Inc.

This is free software; see the source for copying conditions.  There is NO

warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Mac OS: Monterey 12.0.1

Python: 3.8.10

The previously downloaded gfortran version was 11.0.0

**Comment by 3fon3fonov** [comment] 2022-01-11 20:58
The problem is that your fortran77 binaries are not compiled for some reason. The RV part + the stability (N-body) is all written in Fortran. In the $exostriker directory, can you please run:

$ bash install_f77_opt.sh -O3


And report what you get? 


p.s. I doubt this is a problem, but can you switch to from zsh to bash shell?

**Comment by cdesgrange** [comment] 2022-01-12 11:29
Where is the file  install_f77_opt.sh ? I do not find it. 
Perhaps I do not  have it as I installed gcc and gfortran via brew?

What I did:

I changed my zsh to bash by running 

% chsh -s /bin/bash

I closed my terminal, opened a new one, (to switch effectively to zsh to bash shell). Then I ran :

$ bash install_f77_opt.sh -O3
bash: install_f77_opt.sh: No such file or directory

I checked my $PATH, 

$ echo $PATH

here it is:
/Users/user/opt/anaconda3/envs/exostriker_env_again/bin:/Users/user/opt/anaconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin/python3:/usr/local/lib/python3.9/site-packages:/usr/local/opt/python@3.9/libexec/bin:/usr/bin/java:/Library/TeX/texbin


Just to let know, I also tried 

$ bash /usr/local/bin/install_f77_opt.sh -O3 

(I thought it might be located there)

and before changing of shell:
% zsh install_f77_opt.sh -O3 
% zsh /usr/local/bin/install_f77_opt.sh -O3

**Comment by 3fon3fonov** [comment] 2022-01-13 09:55
No no.... 

Let's assume you do a git clone:

```
$ git clone https://github.com/3fon3fonov/exostriker
$ cd exostriker
$ ls 
LICENSE                       docs                 
MANIFEST.in                   exostriker           scripts
Notebook_and_script_examples   setup.py
README.md                     exostriker_gui.py
README_for_installation     

```

You see, there is another exostriker directory. Now do:

```
$ cd exostriker
$ ls 
__init__.py   autosave        gui.py              install_swift.sh  source
 datafiles       lib               stability
 exported_plots  install_f77_opt.sh  mcmc              svg2pdf.sh

$ bash install_f77_opt.sh -O3 
```

And see what's happening. 

When you will be at the MPIA?

**Comment by 3fon3fonov** [comment] 2022-02-18 12:37
Due to low activity and unclear nature of the problem, I am closing. Please re-open if you still need assistance, or just write me on trifonov@mpia.de

**Closed by 3fon3fonov** 2022-02-18 12:37 UTC
Labels: unclear
