### ISSUE TITLE
<class 'OSError'> Could not load shared object file: libllvmlite.so

### ISSUE THREAD

**Issue by jordibp99** [3fon3fonov/exostriker#65] opened 2020-10-25 21:20 UTC
I try to execute exostriker and this bug appears:

<class 'OSError'> Could not load shared object file: libllvmlite.so <traceback object at 0x7f4d411fdfc8>
===== 2020.10.25 22:10:25 =====
Traceback (most recent call last):
  File "/usr/local/bin/exostriker", line 4, in <module>
    __import__('pkg_resources').run_script('exostriker==0.50', 'exostriker')
  File "/usr/local/lib/python3.6/dist-packages/setuptools-50.3.2-py3.6.egg/pkg_resources/__init__.py", line 650, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.6/dist-packages/setuptools-50.3.2-py3.6.egg/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/exostriker-0.50-py3.6.egg/EGG-INFO/scripts/exostriker", line 2, in <module>
    import exostriker
  File "/usr/local/lib/python3.6/dist-packages/exostriker-0.50-py3.6.egg/exostriker/__init__.py", line 1, in <module>
    from exostriker import gui
  File "/usr/local/lib/python3.6/dist-packages/exostriker-0.50-py3.6.egg/exostriker/gui.py", line 76, in <module>
    from detrend_window import DetrendWindow
  File "/usr/local/lib/python3.6/dist-packages/exostriker-0.50-py3.6.egg/exostriker/lib/detrend_window.py", line 15, in <module>
    from wotan import flatten
  File "/usr/local/lib/python3.6/dist-packages/wotan-1.9-py3.6.egg/wotan/__init__.py", line 3, in <module>
    from wotan.flatten import flatten
  File "/usr/local/lib/python3.6/dist-packages/wotan-1.9-py3.6.egg/wotan/flatten.py", line 12, in <module>
    from wotan.cofiam import detrend_cofiam, detrend_cosine
  File "/usr/local/lib/python3.6/dist-packages/wotan-1.9-py3.6.egg/wotan/cofiam.py", line 2, in <module>
    from numba import jit
  File "/usr/local/lib/python3.6/dist-packages/numba-0.51.2-py3.6-linux-x86_64.egg/numba/__init__.py", line 14, in <module>
    from numba.core import config
  File "/usr/local/lib/python3.6/dist-packages/numba-0.51.2-py3.6-linux-x86_64.egg/numba/core/config.py", line 16, in <module>
    import llvmlite.binding as ll
  File "/usr/local/lib/python3.6/dist-packages/llvmlite-0.34.0-py3.6.egg/llvmlite/binding/__init__.py", line 4, in <module>
    from .dylib import *
  File "/usr/local/lib/python3.6/dist-packages/llvmlite-0.34.0-py3.6.egg/llvmlite/binding/dylib.py", line 3, in <module>
    from llvmlite.binding import ffi
  File "/usr/local/lib/python3.6/dist-packages/llvmlite-0.34.0-py3.6.egg/llvmlite/binding/ffi.py", line 153, in <module>
    raise OSError("Could not load shared object file: {}".format(_lib_name))
OSError: Could not load shared object file: libllvmlite.so

Aborted (core dumped)

I've tried to update numba but the problem persists.

**Comment by 3fon3fonov** [comment] 2020-10-25 23:34
Strange problem. I just tried windows10, linux ubuntu and Mac OS install and the Exo-Striker works with no problem. First, please report your OS.

Also, you install the tool via pip, yes? Please confirm.

It seems the problem comes from “wotan” and it's dependencies. Try: 

$ python3 -m pip install wotan -U

???
It may fix your problem?

**Comment by jordibp99** [comment] 2020-10-26 08:26
I'm working in ubuntu and I installed it via pip. During the installation process I had several issues but I tried to solve them each one individually.

I've tried installing wotan and downgrading numba but the bug continues.

**Comment by 3fon3fonov** [comment] 2020-10-26 09:18
I would appreciate to know, the version of your Ubuntu + the "issues" you had. These might be suggestive what your probem is. 


If you have these requrments (in the setup.py):

numpy>=1.16.6
scipy>=1.2.1
matplotlib==3.2.1
formlayout==1.2.0
PyQt5==5.9.2
jupyter
jupyter-client
ipykernel
qtconsole
pathos>=0.2.5
emcee>=3.0.2
corner>=2.1.0
celerite>=0.3.1
batman-package>=2.4.6
transitleastsquares==1.0.24
dynesty>=1.0.1
ttvfast>=0.3.0
wotan>=1.7

Everything should work, except if you are having python3.8 (which I think you don't), then PyQt5>=5.10.x


Please run: 

$exostriker -debug 

and copy-paste the output here (especially the dependecies list that will be printed).
If this fails try a git clone first and power the GUI via the exostriker_gui.py :

$ git clone https://github.com/3fon3fonov/exostriker
$ cd exostriker

$ python3 exostriker_gui.py 

or 

$ python3 exostriker_gui.py -debug # in case of problems

**Comment by jordibp99** [comment] 2020-10-26 13:02
I'm working with Ubuntu 18.04.5 LTS. The issues I found were related with modules that were supossed to install automatically during the installation process but I had to do individually. I remember matplotlib, pyqt5 or pathos. But once I installed them, the installation process continued.

I have all the requirements except pyqt5, which I had to downgrade. However, still appears the same error.

Doing the debug I get the same error:

<class 'OSError'> Could not load shared object file: libllvmlite.so <traceback object at 0x7f62de2a3c48>
===== 2020.10.26 13:10:49 =====
Traceback (most recent call last):
  File "/usr/local/bin/exostriker", line 4, in <module>
    __import__('pkg_resources').run_script('exostriker==0.50', 'exostriker')
  File "/usr/local/lib/python3.6/dist-packages/setuptools-50.3.2-py3.6.egg/pkg_resources/__init__.py", line 650, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.6/dist-packages/setuptools-50.3.2-py3.6.egg/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/exostriker-0.50-py3.6.egg/EGG-INFO/scripts/exostriker", line 2, in <module>
    import exostriker
  File "/usr/local/lib/python3.6/dist-packages/exostriker-0.50-py3.6.egg/exostriker/__init__.py", line 1, in <module>
    from exostriker import gui
  File "/usr/local/lib/python3.6/dist-packages/exostriker-0.50-py3.6.egg/exostriker/gui.py", line 76, in <module>
    from detrend_window import DetrendWindow
  File "/usr/local/lib/python3.6/dist-packages/exostriker-0.50-py3.6.egg/exostriker/lib/detrend_window.py", line 15, in <module>
    from wotan import flatten
  File "/usr/local/lib/python3.6/dist-packages/wotan-1.9-py3.6.egg/wotan/__init__.py", line 3, in <module>
    from wotan.flatten import flatten
  File "/usr/local/lib/python3.6/dist-packages/wotan-1.9-py3.6.egg/wotan/flatten.py", line 12, in <module>
    from wotan.cofiam import detrend_cofiam, detrend_cosine
  File "/usr/local/lib/python3.6/dist-packages/wotan-1.9-py3.6.egg/wotan/cofiam.py", line 2, in <module>
    from numba import jit
  File "/home/jordi/.local/lib/python3.6/site-packages/numba/__init__.py", line 11, in <module>
    from . import config, errors, _runtests as runtests, types
  File "/home/jordi/.local/lib/python3.6/site-packages/numba/config.py", line 19, in <module>
    import llvmlite.binding as ll
  File "/usr/local/lib/python3.6/dist-packages/llvmlite-0.34.0-py3.6.egg/llvmlite/binding/__init__.py", line 4, in <module>
    from .dylib import *
  File "/usr/local/lib/python3.6/dist-packages/llvmlite-0.34.0-py3.6.egg/llvmlite/binding/dylib.py", line 3, in <module>
    from llvmlite.binding import ffi
  File "/usr/local/lib/python3.6/dist-packages/llvmlite-0.34.0-py3.6.egg/llvmlite/binding/ffi.py", line 153, in <module>
    raise OSError("Could not load shared object file: {}".format(_lib_name))
OSError: Could not load shared object file: libllvmlite.so

Aborted (core dumped)

**Comment by 3fon3fonov** [comment] 2020-10-26 13:21
Still, I will need the dependencies list after:

$exostriker -debug

Can you get it in general?



Also, please try:

$ git clone https://github.com/3fon3fonov/exostriker
$ cd exostriker

$ python3 exostriker_gui.py

or

$ python3 exostriker_gui.py -debug # in case of problems


Which version of numba you have?



This is not a bug of the Exo-Striker. What happens if you do:

$ python3 -m IPython

In [1]: import wotan


if the bug presist in wotan, I think you should open a Issue here: 

https://github.com/hippke/wotan/issues

Anyway, I am very interested on how this will develop.

**Comment by jordibp99** [comment] 2020-10-26 18:55
When I type the debug no list of dependencies appear. Just what I've pasted before.

From numba I've got the 0.43.1 version.

When I import wotan, the OSError appears:

In [1]: import wotan
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-1-e7c7db287cef> in <module>
----> 1 import wotan

/usr/local/lib/python3.6/dist-packages/wotan-1.9-py3.6.egg/wotan/__init__.py in <module>
      1 from __future__ import division, print_function
      2 from wotan.t14 import t14
----> 3 from wotan.flatten import flatten
      4 from wotan.slide_clipper import slide_clip
      5 from wotan.helpers import transit_mask

/usr/local/lib/python3.6/dist-packages/wotan-1.9-py3.6.egg/wotan/flatten.py in <module>
     10 # wotan
     11 import wotan.constants as constants
---> 12 from wotan.cofiam import detrend_cofiam, detrend_cosine
     13 from wotan.gp import make_gp
     14 from wotan.huber_spline import detrend_huber_spline

/usr/local/lib/python3.6/dist-packages/wotan-1.9-py3.6.egg/wotan/cofiam.py in <module>
      1 from __future__ import print_function, division
----> 2 from numba import jit
      3 import numpy as np
      4 import wotan.constants as constants
      5 

~/.local/lib/python3.6/site-packages/numba/__init__.py in <module>
      9 import warnings
     10 
---> 11 from . import config, errors, _runtests as runtests, types
     12 
     13 # Re-export typeof

~/.local/lib/python3.6/site-packages/numba/config.py in <module>
     17 
     18 
---> 19 import llvmlite.binding as ll
     20 
     21 IS_WIN32 = sys.platform.startswith('win32')

/usr/local/lib/python3.6/dist-packages/llvmlite-0.34.0-py3.6.egg/llvmlite/binding/__init__.py in <module>
      2 Things that rely on the LLVM library
      3 """
----> 4 from .dylib import *
      5 from .executionengine import *
      6 from .initfini import *

/usr/local/lib/python3.6/dist-packages/llvmlite-0.34.0-py3.6.egg/llvmlite/binding/dylib.py in <module>
      1 from ctypes import c_void_p, c_char_p, c_bool, POINTER
      2 
----> 3 from llvmlite.binding import ffi
      4 from llvmlite.binding.common import _encode_string
      5 

/usr/local/lib/python3.6/dist-packages/llvmlite-0.34.0-py3.6.egg/llvmlite/binding/ffi.py in <module>
    151         break
    152 else:
--> 153     raise OSError("Could not load shared object file: {}".format(_lib_name))
    154 
    155 

OSError: Could not load shared object file: libllvmlite.so

I will adress this problem to the wotan github. As other astro-software, I had only had systemic 2 but I  already deleted. The problem still persists.

Thanks for all the help!

**Comment by 3fon3fonov** [comment] 2020-10-26 19:00
Well, you need to open a wotan issue, but please keep me updated. I might have to remove wotan from the dependencies and only keep it optional. 

Good luck!

**Comment by 3fon3fonov** [comment] 2020-10-26 20:56
OK, now I made wotan optional. If you don't have, the Exo-Striker will just prompt "Wotan not found" and should power without a problem. Of course, you will not be able to detrend transit data, unless successfully install it. 

Please try removing wotan 

$python3 -m pip uninstall wotan

and then:

$ python3 -m pip install git+https://github.com/3fon3fonov/exostriker -U 

$ exostriker

should power the GUI.

**Comment by jordibp99** [comment] 2020-10-26 21:53
Thanks a lot for everything!
I've tried what you said and I've downloades succesfully but when I try to execute it, it aborts because there is no wotan, as I have uninstall it.

<class 'ModuleNotFoundError'> No module named 'wotan' <traceback object at 0x7ff7442349c8>
===== 2020.10.26 22:10:14 =====
Traceback (most recent call last):
  File "exostriker_gui.py", line 2, in <module>
    import exostriker
  File "/home/jordi/exostriker/exostriker/__init__.py", line 1, in <module>
    from exostriker import gui
  File "/home/jordi/exostriker/exostriker/gui.py", line 76, in <module>
    from detrend_window import DetrendWindow
  File "/home/jordi/exostriker/exostriker/lib/detrend_window.py", line 15, in <module>
    from wotan import flatten
ModuleNotFoundError: No module named 'wotan'

Aborted (core dumped)

**Comment by 3fon3fonov** [comment] 2020-10-26 22:10
But I think you need to upgrade the tool. 

File "/home/jordi/exostriker/exostriker/lib/detrend_window.py", line 15, in
from wotan import flatten

Line 15 in detrend_window.py does not exist anymore.

Have you done as I said:

$ python3 -m pip install git+https://github.com/3fon3fonov/exostriker -U

?

if yes, you may try to remove exostriker and then install it again: 

$ python3 -m pip uninstall exostriker

$ python3 -m pip install git+https://github.com/3fon3fonov/exostriker

**Comment by jordibp99** [comment] 2020-10-29 10:42
It looks like it finally works!
But there are some issues with the dessign of the program:

![image](https://user-images.githubusercontent.com/73445597/97556042-3142ef80-19d9-11eb-8380-b7a738bcf8ee.png)

I've tried to reduce the size of the font to 6 but still I can't see the planet parameters.

Additionally, during the installation process this error appeared:

ERROR: spyder 4.1.4 requires pyqtwebengine<5.13; python_version >= "3", which is not installed.
ERROR: spyder 4.1.4 has requirement pyqt5<5.13; python_version >= "3", but you'll have pyqt5 5.15.1 which is incompatible.

So I searched about this error and I found that it was because the only compatible version with spyder was pyqt5==5.12. So I downgraded it, and for the first time I was able to install exostriker, although exostriker recquires pyqt5>=5.15.0. The screenshot of the program is with this configuration with a downgraded version of pyqt5.

So I thought maybe this design problem was with this dowgraded version of pyqt5. I reinstalled spyder in order to look if an updated version of spyder would accept pyqt5>5.15.0. And this error appeared:

pyrsistent requires Python '>=3.5' but the running Python is 2.7.17

Which is something that surprised me as when I checked for the python version, it said that I was working with 3.8.3.

So I created a conda environment to work with python 3.8.3 specifically and I installed spyder correctly. But then, when I tried to execute exostriker, the problem with wotan appeared. The first problem I talked about the days before.

However, when I leave this anaconda environment, exostriker works fine but with this dessign issues. I still haven't checked to fit radial velocity data as I still have to understand how to convert my data in a format that exostriker accepts.

Thank you for your time!

**Comment by 3fon3fonov** [comment] 2020-10-29 16:02
WOW! The Exo-Striker looks horrible on your WM :))) I bet this is due to the resolution of your screen. Increase the resolution and the tool will appear fine.  Unfortunately, I cannot help with Anaconda builds. I hear from other people that they have problems with Anaconda dependencies, but this is not an Exo-Striker problem. 

The Rv format is at least three columns with:

BJD    RV [m/s]    sigma RV [m/s]


So I am closing this as solved!

**Closed by 3fon3fonov** 2020-10-29 16:02 UTC
Labels: external package problem
