### ISSUE TITLE
OpenBLAS : Program will terminate because you tried to start too many threads.

### ISSUE THREAD

**Issue by mzechmeister** [3fon3fonov/exostriker#29] opened 2019-10-04 14:52 UTC
After some time, I often get this error.
There is nothing special or heavy, that was executed.

**Comment by 3fon3fonov** [comment] 2019-10-06 13:29
Thanks for sharing this very strange bug.... I had never seen this error in any of the tested OS distributions. Can you please share the following info:
* OS (and version)
* numpy version
* scipy version
* PyQt5 version
* OpenBLAS version.

I will try to reproduce this behavior.

**Comment by mzechmeister** [comment] 2019-10-07 07:18
* openSUSE Leap v15.0
* numpy 1.14.5
* scipy 1.1.0
* exostriker 4acfa3cebbdb162217f3a3d33e001f8f2ec8aa2c

PyQt5 and openblas (/usr/lib64/libopenblas_pthreads.so.0): How do it get it?

**Comment by 3fon3fonov** [comment] 2019-10-07 18:22
for PyQt4
from PyQt5.Qt import PYQT_VERSION_STR
print("PyQt version:", PYQT_VERSION_STR)


on my openSUSE Leap v15.0 i have the same scipy and numpy...
can you try:

import numpy as np
np.show_config()

**Comment by mzechmeister** [comment] 2019-10-09 07:20
What I often do is pressing `fit` and switching between `Simplex` and `L-M`.

**Comment by 3fon3fonov** [comment] 2019-10-09 07:45
The only thing that is sufficiently different between yours and my setup is that I am using 'PyQt version:', '5.5.1'. The problem must be in numpy, or scipy, which both depend on OpenBLAS. 

Switching between L-M and Sipliex is harmless, but when you press "fit" it does some operations mostly done with numpy. Scipy is only used to find the peaks on the GLS periodogram.
So I am almost sure the problem is in some numpy operation, but I can't reproduce the error at the moment.... When the error occurs, did the GUI crashes or you only get a crash message on the stdout/stderr window? This is an important lead.

Looking at the OpenBLAS issue box on the GitHub I ended up here:

https://github.com/xianyi/OpenBLAS/issues/1735

people try different things with mixed success like:

export OMP_NUM_THREADS=1
export VECLIB_MAXIMUM_THREADS=1
export OPENBLAS_NUM_THREADS=1

if these do not work, you may consider reinstalling OpenBlas

**Comment by 3fon3fonov** [comment] 2019-10-28 07:53
I added 

`os.environ["OPENBLAS_MAIN_FREE"] = "1"`

at the beginning of es_gui.py. This has no effect on my system(s), but might improve others like yours. Please report if you keep seeing this weird OpenBLAS related crash.

**Comment by 3fon3fonov** [comment] 2019-11-30 14:47
Mathias, I believe this is a problem with your system. I am closing, but, if someone else experiences 
the same problem, please re-open.

**Closed by 3fon3fonov** 2019-11-30 14:47 UTC
