### ISSUE TITLE
¨TypeError: object() takes no parameters¨ when started with Py3

### ISSUE THREAD

**Issue by victor230110997** [3fon3fonov/exostriker#55] opened 2020-03-02 10:47 UTC
Hi @3fon3fonov 

I was using exostriker in Windows 10 until I did `git pull` to update this Saturday. Since then, I only got next errors when I try to open exostriker through Ubuntu. I decided to uninstall everything and to start againg but I get same errors.

`/usr/local/lib/python3.6/dist-packages/numba/errors.py:137: UserWarning: Insufficiently recent colorama version found. Numba requires colorama >= 0.3.9`
`warnings.warn(msg)`
`QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-victor'`
`===== 2020.03.02 11:03:46 =====`
`Traceback (most recent call last):`
`File "es_gui.py", line 6971, in <module>`
`main()`
`File "es_gui.py", line 6954, in main`
`window = Exo_striker()`
`File "es_gui.py", line 6474, in __init__`
`self.console_widget = ConsoleWidget_embed(font_size = 9)`
`File "./lib/Jupyter_emb.py", line 24, in __init__`
`self.kernel_client = self._kernel_manager.client()`
`File "/usr/local/lib/python3.6/dist-packages/qtconsole/base_frontend_mixin.py", line 63, in kernel_client`
` if kernel_client.channels_running:`
`File "/usr/local/lib/python3.6/dist-packages/jupyter_client/client.py", line 141, in channels_running`
`self.control_channel.is_alive())`
`File "/usr/local/lib/python3.6/dist-packages/jupyter_client/client.py", line 200, in control_channel`
`socket, self.session, self.ioloop`
`TypeError: object() takes no parameters`

Is there any solution? What can I do?

Thanks for your help.

**Comment by 3fon3fonov** [comment] 2020-03-02 12:39
The problem is almost certainly outside of the Exo-striker. Please try to upgrade your qtconsole version. Which qtconsole are you using at the moment? 

Try:

sudo pip install qtconsole -U

and report. I might need to try it my self on Win10 to reproduce the error.

**Comment by victor230110997** [comment] 2020-03-02 19:20
Hi @3fon3fonov 

I tried with `sudo pip install qtconsole -U` and the terminal output said it's already up-to-date and then, trying to open Exo-striker I get the same error as before.

**Comment by 3fon3fonov** [comment] 2020-03-02 21:38
Hi Victor, 

Thank you for reporting this problem! I can confirm that the Exo-Striker is currently crashing when used with Py3 on Win10. I don't understand the reason, however... I just power an old Win10 OS with ES-Py3 installation that was 100% working in the past. I have not started any "git pull" or updated any packages apart that Win10 as usual wanted to perform some updates. So my guess is that this has nothing to do with my updates, but somehow related to the Win10, although I still don't get how Win10 updates can interfere the Linux subsystem Py3 packages. I will investigate and I will let you know. However, the Py2 installation works fine!

See:
![ES_win10_py2](https://user-images.githubusercontent.com/44244057/75719691-822d0780-5cd5-11ea-9b46-b9be97f7e408.png)

If it is urgent for you to make the ES working, for now try Py2 install. Keep in mind that I encountered a couple of problems with the "installers/linux_debian_install.sh" script. It seems that python2-numpy, python2-scipy, etc are not available anymore. you need to change python2-numpy --> python-numpy, etc, or install via pip manually. Also Py2 installation will crash if you use Gaussian processes in your analysis. See: https://github.com/3fon3fonov/exostriker/issues/23 

Meanwhile, please change the title to reflect the exact problem (e.g. " TypeError: object() takes no parameters" when started with Py3 on Win10").

Also: 
```
/usr/local/lib/python3.6/dist-packages/numba/errors.py:137: UserWarning: Insufficiently recent colorama version found. Numba requires colorama >= 0.3.9
warnings.warn(msg)
```
is fixed by:


sudo pip install colorama -U (or pip2 from python2 and pip3 for python3)

I will keep you posted.

**Comment by 3fon3fonov** [comment] 2020-03-02 23:40
Ok I was wrong! I must have updated the linux Kernel on that Win10.

It turned out that this is general Py3 problem not only Win10. 

The fix (for now) is to downgrade the "jupyter_client"

So do the following:

```
sudo pip3 uninstall jupyter_client
sudo pip3 install jupyter_client==5.3.1
```

Please tell me if this fix worked for you

**Comment by victor230110997** [comment] 2020-03-03 01:57
Hi @3fon3fonov 

It worked for me too, thank you so much.

**Comment by 3fon3fonov** [comment] 2020-03-03 13:06
The bug was already reported by several people. 

https://github.com/jupyter/jupyter_client/issues/523

I expect that this will be resolved soon. I will keep the issue open until there is a more permanent solution using the newest version of jupyter-client

**Comment by 3fon3fonov** [comment] 2020-03-21 22:33
This issue was fixed by:

https://github.com/ipython/ipykernel/issues/492

and 

https://github.com/jupyter/jupyter_client/issues/532

so you should be able to boot the Exo-Striker on a fresh install.

If similar problems occur, please upgrade your ipykernel and also perhaps the jupyter-client 

E.g.
```
sudo pip3 intsall jupyter-client -U
sudo pip3 install ipykernel -U
```

**Closed by 3fon3fonov** 2020-03-21 22:33 UTC
